camera_info:
  image_width: 800
  image_height: 600
stop_line_positions:
    - [1148.56, 1184.65]
    - [1559.2, 1158.43]
    - [2122.14, 1526.79]
    - [2175.237, 1795.71]
    - [1493.29, 2947.67]
    - [821.96, 2905.8]
    - [161.76, 2303.82]
    - [351.84, 1574.65]
# bypass the traffic light classifier, use the light.state from simulator instead.
bypass_light_classify: false
force_to_yellow: false
#model: "light_classification/model/ssd_mobile_sim_5k/frozen_inference_graph.pb"
model: "light_classification/model/output_20k_ssd_inception_alex_data/frozen_inference_graph.pb"
